// Descriptions and call examples for existing upstream assets. No executable
// code is accepted from the UI; the drawing studio uses an explicit dispatch.
window.ElementCatalog = [
  {id:'clawd',kind:'character',name:'Clawd',subtitle:'共享主角',scope:'共享组件',file:'clawd.js',api:'clawd(x, y, u, options)',description:'方块身体、四条短腿和两只眼睛。位置、尺寸、颜色、手臂与表情可独立控制。',controls:'x / y / u · aL / aR · eyes / mouth · col / dk / lt',prepare:'保留角色绘图函数与共用画笔；为新形象修改身体、五官和比例。',drive:'分镜代码计算位置和姿态，再调用 clawd()。',code:'clawd(960, 830, 60, { eyes: "happy", aR: 1.2 });'},
  {id:'researcher',kind:'character',name:'Researcher',subtitle:'研究员',scope:'共享组件',file:'cast.js',api:'researcher(x, y, s, options)',description:'白大褂、圆眼镜的人物，支持走路、跑步、坐下、背面以及手持道具。',controls:'aL / aR · walk / run · sit / back · eyes · coat / pants',prepare:'加载 cast.js 以及 Clawd 的共用表情、动作和几何工具。',drive:'把姿态参数传给 researcher()；handL / handR 可以在手的位置画道具。',code:'researcher(960, 830, 40, { eyes: "wide", aR: 1.2 });'},
  {id:'troupe',kind:'character',name:'群演 Clawd',subtitle:'同一角色的组合',scope:'组合用法',file:'clawd.js',api:'多次调用 clawd() / dancer()',description:'不同帽子、颜色和动作的 Clawd，组成舞者、工人或舞台工作人员。',controls:'hat · col · dancer 的 style / seed · 每人的位置',prepare:'复用一个角色函数，为每名群演准备位置、装饰和动作配置。',drive:'循环调用 clawd() 或 dancer()，形成整齐或错开的群体动作。',code:'dancer(640, 830, 38, "wave", t, { hat: "hard" });\ndancer(1000, 830, 38, "hop", t, { hat: "crown" });\ndancer(1360, 830, 38, "sway", t, { hat: "party" });'},
  {id:'sydney',kind:'character',name:'Sydney-Clawd',subtitle:'粉色爱心眼变体',scope:'章节导出',file:'ch/c03_takeoff.js',api:'CAST.sydney(x, y, s, t, options)',description:'粉色身体、爱心眼、睫毛和蝴蝶结；在原作章节中定义，并导出供其他章节调用。',controls:'Clawd 姿态参数 · bow · eyes · flip',prepare:'加载对应章节及共享依赖，或把实现连同私有辅助函数一起提取。',drive:'通过 CAST.sydney() 传入时间和姿态，沿用既定造型。',code:'CAST.sydney(960, 850, 48, t, { aR: 1.1 });'},
  {id:'gato',kind:'character',name:'Gato-Clawd',subtitle:'猫耳与尾巴变体',scope:'章节导出',file:'ch/c05_obsolete.js',api:'CAST.gato(x, y, s, t, options)',description:'在 Clawd 上增加猫耳、胡须和摆动尾巴，仍复用主体角色接口。',controls:'ears / perk / twitch · bow · Clawd 姿态参数',prepare:'保留章节内部的耳朵、尾巴、曲线辅助函数，以及 clawd.js。',drive:'时间驱动尾巴；参数控制耳朵、表情和身体动作。',code:'CAST.gato(1080, 850, 48, t, { eyes: "happy", perk: .5 });'},
  {id:'shoggoth',kind:'character',name:'Shoggoth',subtitle:'多眼触手怪物',scope:'章节导出',file:'ch/c02_chorus1.js',api:'CAST.shoggoth(x, y, s, t, options)',description:'有多只眼睛和触手，外面可戴笑脸面具。时间驱动身体与触手变化。',controls:'mask · wave · bow · flip',prepare:'加载章节导出的函数及其内部触手和面具辅助代码。',drive:'用 mask 控制面具状态，用时间控制触手动作。',code:'CAST.shoggoth(960, 870, 46, t, { mask: .25 });'},
  {id:'basilisk',kind:'character',name:'Basilisk',subtitle:'戴王冠的蛇形怪物',scope:'章节导出',file:'ch/c04_chorus2.js',api:'CAST.basilisk(x, y, s, t, options)',description:'身体沿弯曲的脊柱绘制，可升起、摇摆、张嘴，也可呈现为舞台木偶。',controls:'rise · bow · open · sway · puppet · eyes',prepare:'保留章节的脊柱、头部、王冠等绘图实现。尺寸参数与其他角色不完全相同。',drive:'时间驱动身体摇摆；rise / open 等参数控制出现和张嘴。',code:'CAST.basilisk(1050, 920, 30, t, { open: .3, eyes: "wide" });'},
  {id:'chinchilla',kind:'character',name:'Chinchilla',subtitle:'毛茸茸的小动物',scope:'章节导出',file:'ch/c07_scale.js',api:'CAST.chinchilla(x, y, s, t, options)',description:'有大耳朵、蓬松身体和尾巴，支持鼓脸颊、抬爪、咀嚼和鞠躬。',controls:'cheeks · paws · chew · bow · eyes · dy / sq',prepare:'保留章节内部的毛发轮廓函数和共享绘画工具。',drive:'通过 cheeks / paws / chew 组合进食动作，或用 bow 鞠躬。',code:'CAST.chinchilla(960, 930, 52, t, { cheeks: .6, paws: .5, chew: .7 });'},
  {id:'stage',kind:'prop',name:'舞台与幕布',subtitle:'共享场景',scope:'共享组件',file:'props.js',api:'stageBack(t, options) + stageFront(t, options)',description:'放射状背景、木地板、侧幕和顶部帷幔，可添加聚光灯和红色警报。',controls:'a / b · spots · curtain · alarm · backdrop',prepare:'把背景、角色和前景绘制顺序规定好；幕布应在角色之后绘制。',drive:'背景 → 角色与道具 → 前景幕布；curtain 控制开合。',code:'stageBack(t, { spots: [[960, PAL.cream]] });\n// 在这里绘制角色与道具\nstageFront(t, { curtain: .2 });'},
  {id:'meter',kind:'prop',name:'温度计式表盘',subtitle:'原作 P(doom) 道具',scope:'共享组件',file:'props.js',api:'meterProp(x, y, s, value, options)',description:'有底座、玻璃管、刻度和标签。液柱高度与颜色由传入的数值决定。',controls:'value 0–100 · cracked · glow · label',prepare:'确定要表达的数值、标签与时间关系；原作数值是编写好的剧情。',drive:'用关键帧计算 value，再把数值传给 meterProp()。',code:'meterProp(960, 920, 1.2, 64, { label: "P(DOOM)", glow: .5 });'},
  {id:'pump',kind:'prop',name:'自行车打气筒',subtitle:'可动把手与软管',scope:'共享组件',file:'props.js',api:'pumpProp(x, y, s, h, hoseTo)',description:'把手高度可改变，软管可以连到指定坐标；原作把按压对齐音乐节拍。',controls:'h 0–1 · hoseTo · pumpH(t)',prepare:'定义打气筒位置、软管终点和角色手与把手的接触关系。',drive:'pumpH(t) 按节拍计算把手高度；角色手臂须用代码同步。',code:'pumpProp(840, 870, 1.8, pumpH(t), [1260, 710]);'},
  {id:'spotlight',kind:'prop',name:'聚光灯',subtitle:'光锥与地面光斑',scope:'共享组件',file:'props.js',api:'spotlight(x, color)',description:'用低透明度水彩形状画光锥和地面光斑。',controls:'x · color · 绘制顺序',prepare:'准备背景对比和光源位置，让光锥在画面中可辨认。',drive:'改变光源 x 或颜色；需要移动时，把 x 写成时间函数。',code:'spotlight(960, PAL.ochre);'},
  {id:'sunburst',kind:'prop',name:'放射状背景',subtitle:'舞台视觉纹样',scope:'共享组件',file:'props.js',api:'sunburst(cx, cy, a, b, rot, n, r, op)',description:'围绕中心绘制交替颜色的扇形，可以旋转并改变颜色、数量和透明度。',controls:'中心 · 两种颜色 · rot · n · r · op',prepare:'确定画面焦点、两色组合和纹样尺度。',drive:'例如用 rot = t * .12，让背景缓慢旋转。',code:'sunburst(960, 540, PAL.rose, PAL.ochre, t * .12);'},
  {id:'geometry',kind:'prop',name:'几何形状与心形',subtitle:'新道具的基础',scope:'绘画基础',file:'core.js',api:'rectPts / ellPts / starPts / heartPts + paint',description:'提供形状的点列表，再由 paint() 绘制颜色、纹理和轮廓；可以组合成新道具。',controls:'形状尺寸 · 位置 · wash / fill / ink',prepare:'把新道具拆成形状，定义可动部件。几何与画笔来自 core.js；心形 heartPts() 还需要 clawd.js。',drive:'按当前状态计算形状位置，再调用 paint()。',code:'// heartPts() 定义在 clawd.js，需一并加载\npaint(starPts(960, 450, 130), { wash: PAL.ochre });\npaint(heartPts(960, 740, 85), { fill: PAL.rose });'},
];
