import {createCampProposal,validateCampProposal,addCampVariant,replaceCampGeneration,CAMP_ROLES} from './camp-core.js';
import {validatePlan} from './creation-core.js';
import {fingerprintPlan} from './model-scene-core.js';
import {fineGeometryDiagnostics} from './fine-geometry-core.js';
import {assertFineRefinementPreserved} from './fine-refinement-core.js';
import {openCampScene,applyCampView,campLayoutImage} from './camp-scene.js';
import {buildSceneDelivery} from './scene-delivery.js';
import {buildCampDelivery} from './camp-delivery.js';
const $=id=>document.getElementById(id),endpoint='http://127.0.0.1:4198';
const localServiceAllowed=['localhost','127.0.0.1','[::1]'].includes(location.hostname);
let proposal,scene=null,selectedId=null,busy=true,coarse=false,alive=true,health=false;
let lastJob=null,lastPublished=null;
const active=()=>proposal?.variants.find(v=>v.id===proposal.activeVariantId);
async function dbValue(dbName,storeName,key,value){const db=await new Promise((resolve,reject)=>{const r=indexedDB.open(dbName,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(storeName))r.result.createObjectStore(storeName);};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});try{return await new Promise((resolve,reject)=>{const tx=db.transaction(storeName,value===undefined?'readonly':'readwrite'),r=value===undefined?(key===null?tx.objectStore(storeName).getAll():tx.objectStore(storeName).get(key)):tx.objectStore(storeName).put(value,key);let result;r.onsuccess=()=>result=r.result;tx.oncomplete=()=>resolve(result);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error);});}finally{db.close();}}
const store=(key,value)=>dbValue('tidewater-camp-proposals.v1','proposals',key,value);
const setStatus=m=>$('status').textContent=m;
const showError=e=>{$('error').textContent=e?e.message??String(e):'';$('error').hidden=!e;};
async function fetchJSON(url,options){const r=await fetch(url,options);const data=await r.json();if(!r.ok)throw new Error(data.error??`接口失败 (${r.status})`);return data;}
const post=(route,data)=>fetchJSON(`${endpoint}/${route}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});
function refresh(){for(const e of document.querySelectorAll('button,input,textarea,select'))e.disabled=busy;$('generate').disabled=busy||!health;const entity=proposal?.sourcePlan.entities.find(e=>e.id===selectedId),editable=entity&&!entity.locked&&['cabin','palm','boat','lighthouse'].includes(entity.kind);$('alternative').disabled=busy||!health||!active()?.candidate||!editable;$('scope-help').textContent=editable?'将只修改这个对象，原方案继续保留；范围外几何、材质和朝向会重新核对。':'选中未锁定的小屋、棕榈、船或灯塔，可以创建局部修改方案。';$('coarse').disabled=busy||!active()?.candidate;$('preview').disabled=busy||!proposal;$('publish').disabled=busy||!health||!proposal?.variants.some(v=>v.candidate)||proposal?.variants.some(v=>!v.candidate);$('representation').textContent=active()?.candidate?'模型生成候选 · 待验收':'布局粗模 · 尚未生成';$('stage-title').textContent=active()?.title??'确认这份空间';$('coarse').textContent=coarse?'回到模型方案':'对照粗模';}
function report(){const c=active()?.candidate;$('receipt').textContent=JSON.stringify({sourceFingerprint:fingerprintPlan(proposal.sourcePlan),activeVariant:proposal.activeVariantId,job:lastJob,sceneJob:c?.receipt?.id,geometryJob:c?.geometryReceipt?.id,geometryChecks:c?.geometryChecks,fineEdit:c?.fineEdit,visualQuality:'needs-review',viewState:scene?.getViewState(),published:lastPublished},null,2);}
function flush(){if(!proposal)return;proposal.title=$('title').value;proposal.summary=$('summary').value;proposal.intent=$('intent').value;const object=proposal.objects.find(o=>o.id===selectedId);if(object){object.name=$('object-name').value;object.role=$('role').value;object.description=$('description').value;object.note=$('note').value;}proposal=validateCampProposal(proposal);}
function select(id,focus=true){flush();selectedId=id;renderFields();renderObjects();if(focus)scene?.focusEntity(id);refresh();}
function renderFields(){const object=proposal.objects.find(o=>o.id===selectedId);if(!object)return;$('object-heading').textContent=object.name;$('object-name').value=object.name;$('role').value=object.role;$('description').value=object.description;$('note').value=object.note;$('reference').hidden=!object.reference;$('remove-reference').hidden=!object.reference;if(object.reference)$('reference').src=object.reference.dataUrl;else $('reference').removeAttribute('src');}
function renderObjects(){const container=$('objects');container.replaceChildren();for(const object of proposal.objects){const b=document.createElement('button'),name=document.createElement('span'),sub=document.createElement('small');name.textContent=object.name;const e=proposal.sourcePlan.entities.find(e=>e.id===object.id);sub.textContent=`${CAMP_ROLES[object.role]}${e.locked?' · 空间锁定':''}`;b.append(name,sub);b.setAttribute('aria-pressed',String(object.id===selectedId));b.addEventListener('click',()=>attempt(()=>select(object.id)));container.append(b);}}
function render(){const stays=proposal.objects.filter(o=>o.role==='stay').length;$('title').value=proposal.title;$('summary').value=proposal.summary;$('intent').value=proposal.intent;$('facts').textContent=`${proposal.sourcePlan.world.width} × ${proposal.sourcePlan.world.depth} 米 · ${stays} 间住宿木屋 · ${proposal.sourcePlan.entities.length} 个空间对象`;$('layout').src=campLayoutImage(proposal.sourcePlan,proposal.objects);if(!proposal.objects.some(o=>o.id===selectedId))selectedId=proposal.objects.find(o=>o.role==='stay')?.id??proposal.objects[0]?.id;renderFields();renderObjects();$('variants').replaceChildren();for(const variant of proposal.variants){const b=document.createElement('button');b.textContent=variant.title;b.setAttribute('aria-pressed',String(variant.id===proposal.activeVariantId));b.addEventListener('click',()=>attempt(async()=>{flush();const viewState=scene.getViewState();await display({...proposal,activeVariantId:variant.id},viewState);setStatus('切换方案时保留了同一个镜头，方便比较。');}));$('variants').append(b);}$('views').replaceChildren();for(const view of proposal.views){const b=document.createElement('button');b.textContent=view.name;b.addEventListener('click',()=>applyCampView(scene,view));$('views').append(b);}report();refresh();}
async function display(next,viewState=null){next=validateCampProposal(next);const old=proposal,oldView=scene?.getViewState();scene?.dispose();scene=null;try{scene=await openCampScene({canvas:$('scene'),proposal:next,variantId:next.activeVariantId,viewState,onSelect:id=>attempt(()=>select(id)),onProgress:p=>setStatus(p.detail??p.message??String(p))});proposal=next;coarse=false;lastPublished=await store(`publication:${proposal.id}`)??null;showPublication();render();}catch(error){if(old){proposal=old;scene=await openCampScene({canvas:$('scene'),proposal:old,variantId:old.activeVariantId,viewState:oldView,onSelect:id=>attempt(()=>select(id))});render();}throw error;}}
async function save(message='提案已保存到本机。'){if(!proposal)return;flush();proposal.savedAt=new Date().toISOString();await store(proposal.id,proposal);await store('current',proposal);setStatus(message);report();}
async function attempt(action){if(busy)return;busy=true;showError(null);refresh();try{return await action();}catch(error){showError(error);setStatus('操作未完成，已有提案保留。');}finally{busy=false;refresh();}}
async function job(route,request){let j=await post(route,request);while(['queued','running'].includes(j.status)){lastJob={id:j.id,status:j.status,progress:j.progress,inputViews:request.views.map(v=>v.label)};report();setStatus(`${route==='jobs'?'模型正在制定营地方案':'模型正在完善实际几何'} · ${j.status==='queued'?'排队中':'生成中'}`);await new Promise(resolve=>setTimeout(resolve,1200));if(!alive)throw new Error('页面已关闭；模型回执保留在服务端。');j=await fetchJSON(`${endpoint}/jobs/${j.id}`);}lastJob={id:j.id,status:j.status,receipt:j.receipt,error:j.error};report();if(j.status!=='succeeded')throw new Error(j.error??'模型任务没有完成。');return j;}
function showInputs(views){$('inputs').replaceChildren();for(const view of views){const img=document.createElement('img');img.src=view.dataUrl;img.alt=view.label;img.title=view.label;$('inputs').append(img);}}
function sceneViews(local=false){const viewState=scene.getViewState();scene.setMode(local?'realistic':'coarse');if(local)scene.focusEntity(selectedId);else scene.setView('overview');const views=[{label:'当前语义布局：名称、位置与锁定来自原plan',dataUrl:campLayoutImage(proposal.sourcePlan,proposal.objects)},{label:local?`选中对象 ${selectedId} 当前近景`:'当前场景粗模全景',dataUrl:scene.capture()}];scene.reverseView();views.push({label:local?'该对象另一侧实际画面':'粗模另一侧实际画面',dataUrl:scene.capture()});const reference=proposal.objects.find(o=>o.id===selectedId)?.reference??proposal.sourcePlan.reference;if(reference)views.push({label:`用户外观参考 ${selectedId}`,dataUrl:reference.dataUrl});scene.setViewState(viewState);scene.setMode(active()?.candidate?'realistic':'coarse');coarse=false;showInputs(views);return views;}
function modelIntent(){return `${proposal.intent}\n用途：沿用用户当前场景的概念提案。数量、位置和身份完全以sourcePlan为准；不要引入示例布局的对象。各对象身份与要求：\n${proposal.objects.map(o=>`${o.id}: ${o.name} / ${CAMP_ROLES[o.role]} / ${o.description} ${o.note}`).join('\n')}\n原布局中已存在的木屋应是完整建筑，有连续屋顶、门窗、门廊、支撑和自然木材色，避免箱体或极细部件。保留全部原位置和包络。棕榈采用连续树干、薄叶带和自然下垂。这是需人工验收的概念方案，不宣称照片级。`.slice(0,6000);}
async function generate(){flush();await save('当前提案已保留，模型即将依据布局生成新方案。');const views=sceneViews(),intent=modelIntent(),plan=proposal.sourcePlan;const scheme=await job('jobs',{plan,intent,views,mode:'generate'});const fine=await job('fine-jobs',{plan,intent,views,baseRecipe:scheme.recipe});const candidate={sourcePlan:plan,recipe:scheme.recipe,geometry:fine.geometry,receipt:scheme.receipt,geometryReceipt:fine.receipt,views,geometryViews:views,requestIntent:intent,geometryIterations:[],geometryDiagnostics:fineGeometryDiagnostics(fine.geometry),savedAt:null,delivery:null};const next=replaceCampGeneration(proposal,candidate);await display(next);active().candidate.geometryChecks=scene.getFineGeometryChecks();await save('方案 A 已生成并保存。可以查看木屋近景，再另存局部修改方案。');}
async function alternative(){flush();const original=proposal.variants.find(v=>v.id==='a')?.candidate;if(!original)throw new Error('先生成方案A，再另存局部方案。');const priorView=scene.getViewState();await display({...proposal,activeVariantId:'a'},priorView);const views=sceneViews(true),object=proposal.objects.find(o=>o.id===selectedId),scopeIds=[selectedId],intent=`${proposal.intent.slice(0,2000)}\n仅完善 ${selectedId}（${object.name}），其他对象保持。修改要求：${object.note||'改善选中对象的外观与结构细节，保留原位置和尺度。'}\n查看所附实际近景、背面和参考。只完善指定对象。`.slice(0,6000);const fine=await job('fine-jobs',{plan:proposal.sourcePlan,intent,views,baseRecipe:original.recipe,previousGeometry:original.geometry,scopeIds});const fineEdit=assertFineRefinementPreserved(original.geometry,fine.geometry,proposal.sourcePlan,scopeIds,{baseRecipe:original.recipe});const candidate={...original,geometry:fine.geometry,geometryReceipt:fine.receipt,geometryViews:views,geometryIntent:intent,fineEdit,geometryDiagnostics:fineGeometryDiagnostics(fine.geometry),savedAt:null,delivery:null,geometryIterations:[...(original.geometryIterations??[]),{geometry:original.geometry,receipt:original.geometryReceipt,views:original.geometryViews??original.views,checks:original.geometryChecks,diagnostics:original.geometryDiagnostics??null,fineEdit:original.fineEdit??null,reason:'scoped-refinement'}]};await display(addCampVariant(proposal,candidate,{id:'b',title:'方案 B · 局部调整',description:`仅完善 ${object.name}：${object.note||'改善外观与结构细节'}`}));active().candidate.geometryChecks=scene.getFineGeometryChecks();await save('方案 B 已保存，方案 A 保留。其余对象的几何、材质与朝向核对通过。');}
async function saveSceneDelivery(candidate){const exported=await buildSceneDelivery({scene,candidate,onProgress:p=>setStatus(p.message)}),record=await post('deliveries',{candidate:{...candidate,delivery:null},manifest:exported.manifest});for(const [kind,blob] of [['glb',exported.glbBlob],['project',exported.projectBlob]]){const bytes=await blob.arrayBuffer(),digest=await crypto.subtle.digest('SHA-256',bytes),sha=[...new Uint8Array(digest)].map(v=>v.toString(16).padStart(2,'0')).join('');await fetchJSON(`${endpoint}/deliveries/${record.id}/${kind}`,{method:'POST',headers:{'Content-Type':'application/octet-stream','X-Content-SHA256':sha},body:blob});}candidate.delivery={manifest:exported.manifest,checks:exported.checks,urls:record};}
async function publish(){flush();const originalId=proposal.activeVariantId,viewState=scene.getViewState();for(const variant of [...proposal.variants]){if(!variant.candidate?.delivery?.urls){await display({...proposal,activeVariantId:variant.id},viewState);await saveSceneDelivery(active().candidate);await save('场景文件已落盘，正在整理营地提案…');}}await display({...proposal,activeVariantId:originalId},viewState);const prepared=await buildCampDelivery(proposal,p=>setStatus(p)),record=await post('camp-proposals',{proposal:prepared.proposal,manifest:prepared.manifest});await fetchJSON(`${endpoint}/camp-proposals/${record.id}/project`,{method:'POST',headers:{'Content-Type':'application/octet-stream','X-Content-SHA256':prepared.zipSha256},body:prepared.zipBlob});lastPublished=record;await store(`publication:${proposal.id}`,record);$('viewer-link').href=record.viewerUrl;$('zip-link').href=record.projectUrl;$('delivery').hidden=false;await save(`提案与独立工程已保存。已生成本机浏览链接；工程包含${proposal.variants.length}份方案、对象介绍与真实来源。`);report();}
for(const [key,name] of Object.entries(CAMP_ROLES)){const option=document.createElement('option');option.value=key;option.textContent=name;$('role').append(option);}
$('generate').addEventListener('click',()=>attempt(generate));$('alternative').addEventListener('click',()=>attempt(alternative));$('publish').addEventListener('click',()=>attempt(publish));$('save').addEventListener('click',()=>attempt(()=>save()));$('update-object').addEventListener('click',()=>attempt(async()=>{flush();render();await save('对象名称、用途与介绍已保存。');}));
$('coarse').addEventListener('click',()=>{coarse=!coarse;scene.setMode(coarse?'coarse':'realistic');refresh();});$('reverse').addEventListener('click',()=>scene?.reverseView());$('save-view').addEventListener('click',()=>attempt(async()=>{if(proposal.views.length>=8)throw new Error('最多保存8个视角。');proposal.views.push({id:`view-${crypto.randomUUID().slice(0,8)}`,name:`${proposal.objects.find(o=>o.id===selectedId)?.name??"场景"} · 视角 ${proposal.views.length-2}`,preset:null,entityId:null,state:scene.getViewState()});render();await save('当前镜头已保存到提案中。');}));

$('history').addEventListener('click',()=>attempt(async()=>{
 await save();const records=(await store(null)).filter(p=>p?.format==='tidewater-camp-proposal.v1');
 const unique=[...new Map(records.map(p=>[p.id,p])).values()].sort((a,b)=>(b.savedAt??'').localeCompare(a.savedAt??''));
 $('history-list').replaceChildren();for(const record of unique){const button=document.createElement('button'),label=document.createElement('span'),detail=document.createElement('small');label.textContent=record.title;detail.textContent=`${record.savedAt?new Date(record.savedAt).toLocaleString('zh-CN'):'未保存'} · ${record.variants.length}份方案 · ${record.sourcePlan.entities.length}个对象${record.id===proposal.id?' · 当前':''}`;button.append(label,detail);button.addEventListener('click',()=>attempt(async()=>{await save();await display(record);lastPublished=await store(`publication:${proposal.id}`)??null;showPublication();await save('已恢复历史提案。');$('history-dialog').close();}));$('history-list').append(button);}$('history-dialog').showModal();
}));$('history-close').addEventListener('click',()=>$('history-dialog').close());
function showPublication(){$('delivery').hidden=!lastPublished;if(lastPublished){$('viewer-link').href=lastPublished.viewerUrl;$('zip-link').href=lastPublished.projectUrl;}}
$('example').addEventListener('click',()=>attempt(async()=>{await save('当前提案已保留。');const data=await fetchJSON('./assets/camp/example.json');data.id=crypto.randomUUID();await display(data);await save('已载入六间木屋营地示例，原提案仍在本机。');}));
$('original').addEventListener('click',()=>attempt(async()=>{await save('当前提案已保留。');const data=await fetchJSON('./assets/camp/original.json');data.id=crypto.randomUUID();await display(data);await save('已回到原海岛的25个对象与既有精修结果；六木屋示例仍单独保留。');}));
$('current').addEventListener('click',()=>attempt(async()=>{const pending=await dbValue('tidewater-scene-completion','scenes','fine-candidate'),saved=await dbValue('tidewater-scene-completion','scenes','current'),candidate=pending?.geometry?pending:saved;if(!candidate?.geometry)throw new Error('当前创作页面还没有可引入的精修候选。');await save();const next=addCampVariant(createCampProposal(candidate.sourcePlan),candidate,{id:'a',title:'方案 A · 当前精修场景',description:'来自场景创作页面的实际模型候选。'});await display(next);await save('已引入当前精修场景；原草案与精修记录保持。');}));
$('edit-layout').addEventListener('click',()=>attempt(async()=>{await save();const token=crypto.randomUUID();sessionStorage.setItem(`tidewater-camp-transfer:${token}`,JSON.stringify({plan:proposal.sourcePlan,proposalId:proposal.id}));location.href=`create.html?entry=layout&campTransfer=${token}`;}));
$('pull-layout').addEventListener('click',()=>attempt(async()=>{const draft=await dbValue('tidewater-creation-lab.v1','drafts','current');if(!draft?.plan?.entities.length)throw new Error('请先在绘笔页面保存非空布局。');const plan=validatePlan(draft.plan);if(fingerprintPlan(plan)===fingerprintPlan(proposal.sourcePlan)){setStatus('已保存布局与当前提案相同，无需重新生成。');return;}await save();const next=createCampProposal(plan);next.title=proposal.title;next.summary=proposal.summary;next.intent=proposal.intent;next.objects=next.objects.map(o=>proposal.objects.find(old=>old.id===o.id)??o);await display(next);await save('布局已引入。此前提案已保留；当前粗模需要重新生成方案。');}));
function downloadJSON(){flush();const blob=new Blob([JSON.stringify(proposal,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='camp-proposal.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
$('export').addEventListener('click',()=>attempt(downloadJSON));$('import').addEventListener('click',()=>$('file').click());$('file').addEventListener('change',e=>{const file=e.target.files[0];e.target.value='';if(file)attempt(async()=>{if(file.size>20*1048576)throw new Error('提案文件超过20MiB。');const next=validateCampProposal(JSON.parse(await file.text()));await save();await display(next);await save('营地提案已恢复。');});});
$('reference-file').addEventListener('change',e=>{const file=e.target.files[0];e.target.value='';if(file)attempt(async()=>{
 if(file.size>8*1048576||!/^image\/(png|jpeg|webp)$/u.test(file.type))throw new Error('请选择8MiB以内的PNG、JPEG或WebP图片。');
 const bitmap=await createImageBitmap(file);let reference;
 try{if(bitmap.width>8192||bitmap.height>8192)throw new Error('参考图尺寸超过8192像素。');const scale=Math.min(1,1200/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);let dataUrl=canvas.toDataURL('image/webp',.9);if(dataUrl.length>2*1048576)dataUrl=canvas.toDataURL('image/webp',.65);reference={name:file.name.slice(0,130)+' · 网页参考',dataUrl,width:canvas.width,height:canvas.height};}finally{bitmap.close();}
 flush();validatePlan({...proposal.sourcePlan,reference});proposal.objects.find(o=>o.id===selectedId).reference=reference;renderFields();await save('参考图已保存（长边最多1200像素）。下次选中对象生成时会实际发送给模型。');
});});$('remove-reference').addEventListener('click',()=>attempt(async()=>{proposal.objects.find(o=>o.id===selectedId).reference=null;renderFields();await save('对象参考图已移除。');}));
$('preview').addEventListener('click',()=>attempt(async()=>{await save();const url=`camp-viewer.html?draft=${proposal.id}`;window.open(url,'tidewater-camp-preview');setStatus('已打开本机提案预览。生成并保存工程后，可得到固定本机链接。');}));
addEventListener('pagehide',()=>{alive=false;scene?.dispose();});
try{const saved=await store('current');proposal=saved?validateCampProposal(saved):await fetchJSON('./assets/camp/original.json');if(!saved)proposal.id=crypto.randomUUID();await display(proposal);setStatus(active().candidate?'已恢复当前场景提案。可以完善对象介绍，或创建局部修改版本。':'当前场景粗模已载入。可以先编辑空间，再依据布局生成方案 A。');if(localServiceAllowed){try{const service=await fetchJSON(`${endpoint}/health`);health=service.available===true;}catch{health=false;}}$('service-mode').textContent=health?'本机模型服务已连接，可生成新方案和保存独立工程。':localServiceAllowed?'本机模型服务未连接。已有场景仍可浏览、编辑和导出JSON。':'在线展示版：可浏览与编辑已有提案。新生成及新工程打包需下载源码后启动本机模型服务。';}catch(e){showError(e);if(!scene){proposal=null;setStatus('场景载入失败。请重新打开或导入已保存提案。');}}finally{busy=false;refresh();}
