import * as THREE from 'three';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { HDRLoader } from 'three/addons/loaders/HDRLoader.js';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { clone as cloneRig } from 'three/addons/utils/SkeletonUtils.js';
import { EffectComposer } from 'three/addons/postprocessing/EffectComposer.js';
import { RenderPass } from 'three/addons/postprocessing/RenderPass.js';
import { SSAOPass } from 'three/addons/postprocessing/SSAOPass.js';
import { OutputPass } from 'three/addons/postprocessing/OutputPass.js';
import { CAMERA_LIMITS, COLORS, cameraForView } from './core.js';

const SOURCES=[
  {id:'tee-01',kind:'garment',file:'assets/core-tee.glb',position:[-1.08,0,-.12],color:'ivory'},
  {id:'jacket-01',kind:'garment',file:'assets/field-jacket.glb',position:[1.08,0,-.12],color:'moss'},
  {id:'court-01',kind:'shoes',file:'footwear/court.glb',position:[-1.04,.34,.05],color:'ivory'},
  {id:'boot-01',kind:'shoes',file:'footwear/ridge.glb',position:[1.04,.34,.05],color:'ink'},
];
const DROP_Y={min:.82,max:1.61};
export async function createFitting(host,callbacks={}){
  const world=new THREE.Scene();world.background=new THREE.Color('#e7e7de');world.fog=new THREE.Fog('#e7e7de',10,28);
  const renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.5));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;
  const canvas=renderer.domElement;canvas.setAttribute('aria-label','三维试衣间：按住展样拖到人体上身或脚部，观察衣型与鞋脚贴合');host.append(canvas);
  const camera=new THREE.PerspectiveCamera(33,1,.025,40),controls=new OrbitControls(camera,canvas);controls.enableDamping=false;controls.minDistance=CAMERA_LIMITS.minDistance;controls.maxDistance=CAMERA_LIMITS.maxDistance;controls.minPolarAngle=CAMERA_LIMITS.minPolar;controls.maxPolarAngle=CAMERA_LIMITS.maxPolar;
  let galleryKind='garment';
  let applying=false,held=false,cameraPointer=null,locked=false,lockedCamera=null,cameraInteraction=true,disposed=false,frameId,drag=null;
  function clampCamera(){const old=controls.target.clone();controls.target.x=THREE.MathUtils.clamp(controls.target.x,-CAMERA_LIMITS.maxTargetXZ,CAMERA_LIMITS.maxTargetXZ);controls.target.z=THREE.MathUtils.clamp(controls.target.z,-CAMERA_LIMITS.maxTargetXZ,CAMERA_LIMITS.maxTargetXZ);controls.target.y=THREE.MathUtils.clamp(controls.target.y,CAMERA_LIMITS.minTargetY,CAMERA_LIMITS.maxTargetY);camera.position.add(controls.target.clone().sub(old));const offset=camera.position.clone().sub(controls.target),spherical=new THREE.Spherical().setFromVector3(offset),radius=THREE.MathUtils.clamp(spherical.radius,CAMERA_LIMITS.minDistance,CAMERA_LIMITS.maxDistance),low=Math.max(CAMERA_LIMITS.minPolar,Math.acos(THREE.MathUtils.clamp((CAMERA_LIMITS.maxPositionY-1e-8-controls.target.y)/radius,-1,1))),high=Math.min(CAMERA_LIMITS.maxPolar,Math.acos(THREE.MathUtils.clamp((CAMERA_LIMITS.minPositionY+1e-8-controls.target.y)/radius,-1,1))),polar=THREE.MathUtils.clamp(spherical.phi,low,high);if(Math.abs(radius-spherical.radius)>1e-10||Math.abs(polar-spherical.phi)>1e-10){spherical.radius=radius;spherical.phi=polar;camera.position.copy(controls.target).add(new THREE.Vector3().setFromSpherical(spherical));}}
  const getCamera=()=>{clampCamera();return{position:camera.position.toArray(),target:controls.target.toArray()};};
  function setCamera(value){applying=true;camera.position.fromArray(value.position);controls.target.fromArray(value.target);controls.update();applying=false;}
  setCamera(cameraForView('hero'));
  const composer=new EffectComposer(renderer);composer.addPass(new RenderPass(world,camera));const ao=new SSAOPass(world,camera,1,1);ao.kernelRadius=.05;ao.minDistance=.001;ao.maxDistance=.11;composer.addPass(ao);composer.addPass(new OutputPass());
  const loader=new GLTFLoader();const [avatarAsset,garmentAssets,hdr]=await Promise.all([loader.loadAsync(new URL('./assets/avatar.glb',import.meta.url).href),Promise.all(SOURCES.map(s=>loader.loadAsync(new URL('./'+s.file,import.meta.url).href))),new HDRLoader().loadAsync(new URL('../studio/assets/environment/coastal-day.hdr',import.meta.url).href)]);
  const pmrem=new THREE.PMREMGenerator(renderer),environment=pmrem.fromEquirectangular(hdr);world.environment=environment.texture;world.environmentIntensity=.6;hdr.dispose();pmrem.dispose();
  const mat=(color,roughness=.8,metalness=0)=>new THREE.MeshStandardMaterial({color,roughness,metalness});
  function add(geometry,material,position,parent=world){const mesh=new THREE.Mesh(geometry,material);mesh.position.fromArray(position);mesh.castShadow=mesh.receiveShadow=true;parent.add(mesh);return mesh;}
  const floor=add(new THREE.PlaneGeometry(70,70),mat('#dedfd3'),[0,-.002,0]);floor.rotation.x=-Math.PI/2;
  const ring=add(new THREE.RingGeometry(.46,.468,100),new THREE.MeshBasicMaterial({color:'#a8b59a',side:THREE.DoubleSide,transparent:true,opacity:.55}),[0,.001,0]);ring.rotation.x=-Math.PI/2;ring.castShadow=ring.receiveShadow=false;
  const key=new THREE.DirectionalLight('#fff5dd',3.1);key.position.set(-2.5,5,3.5);key.castShadow=true;key.shadow.mapSize.set(2048,2048);Object.assign(key.shadow.camera,{left:-3,right:3,top:3,bottom:-3,near:.1,far:14});key.shadow.bias=-.00015;key.shadow.normalBias=.006;world.add(key);const fill=new THREE.DirectionalLight('#e4eee3',1.7);fill.position.set(3,3,-3);world.add(fill);world.add(new THREE.HemisphereLight('#f9fae8','#a1ae8e',.45));
  // Authored hangers and rails support complete garment assets; they are scenery.
  const metal=mat('#637b6c',.45,.55),wood=mat('#c4b794',.7);
  const racks=new THREE.Group(),plinths=new THREE.Group();world.add(racks,plinths);plinths.visible=false;
  for(const item of SOURCES.filter(s=>s.kind==='garment')){const [x,,z]=item.position;add(new THREE.CylinderGeometry(.012,.014,1.6,16),metal,[x, .8,z-.18]);add(new THREE.CylinderGeometry(.22,.22,.025,64),metal,[x,.011,z-.18]);const rail=add(new THREE.CylinderGeometry(.012,.012,.23,16),metal,[x,1.6,z-.06]);rail.rotation.x=Math.PI/2;const hangerPoints=[[0,1.60,0],[-.25,1.43,0],[.25,1.43,0],[0,1.60,0]].map(p=>new THREE.Vector3(p[0]+x,p[1],p[2]+z));const hanger=new THREE.Line(new THREE.BufferGeometry().setFromPoints(hangerPoints),new THREE.LineBasicMaterial({color:'#ad9c78'}));world.add(hanger);const hook=add(new THREE.TorusGeometry(.031,.005,6,30,Math.PI*1.5),metal,[x,1.63,z]);hook.rotation.z=Math.PI/2;const cross=add(new THREE.CylinderGeometry(.009,.009,.43,16),wood,[x,1.435,z]);cross.rotation.z=Math.PI/2;}
  for(const child of [...world.children])if((child.isMesh&&child!==floor&&child!==ring)||child.isLine)racks.add(child);
  for(const item of SOURCES.filter(s=>s.kind==='shoes')){const [x,,z]=item.position;const block=add(new THREE.CylinderGeometry(.31,.33,.32,64),mat('#cbd1bd'),[x,.16,z],plinths);block.receiveShadow=true;const top=add(new THREE.CylinderGeometry(.305,.305,.019,64),mat('#e9e8d8'),[x,.329,z],plinths);top.receiveShadow=true;}
  const actor=new THREE.Group();actor.name='registered-fitting-avatar';world.add(actor);
  function instance(asset,kind='garment'){const root=cloneRig(asset.scene),fabric=[];root.traverse(node=>{if(!node.isMesh)return;node.castShadow=node.receiveShadow=true;const copy=material=>{const clone=material.clone();if(clone.name===(kind==='shoes'?'Fitting_ShoeUpper':'Fitting_Fabric'))fabric.push(clone);return clone;};node.material=Array.isArray(node.material)?node.material.map(copy):copy(node.material);});const mixer=new THREE.AnimationMixer(root);for(const name of ['Fitting_Neutral','Fitting_Reach'])if(kind!=='shoes'&&!THREE.AnimationClip.findByName(asset.animations,name))throw Error('试衣素材缺少登记姿态 '+name);if(kind==='shoes'&&!fabric.length)throw Error('鞋素材缺少鞋面材质');return{root,mixer,animations:asset.animations,fabric,kind,pose:null};}
  function pose(instance,value){if(instance.pose===value)return;instance.mixer.stopAllAction();const name=value==='reach'?'Fitting_Reach':'Fitting_Neutral';const clip=THREE.AnimationClip.findByName(instance.animations,name);if(clip){instance.mixer.clipAction(clip).reset().setEffectiveWeight(1).play();instance.mixer.setTime(0);}else if(instance.kind!=='shoes')throw Error('未登记姿态');instance.root.updateMatrixWorld(true);instance.root.traverse(node=>{if(node.isSkinnedMesh){node.skeleton.update();node.computeBoundingBox();node.computeBoundingSphere();}});instance.pose=value;}
  function color(instance,id){const value=COLORS.find(c=>c.id===id);if(!value)throw Error('未登记面料颜色');for(const material of instance.fabric)material.color.set(value.color);}
  const avatar=instance(avatarAsset);actor.add(avatar.root);pose(avatar,'neutral');
  const worn=new Map(),gallery=new Map(),ghosts=new Map();
  for(let i=0;i<SOURCES.length;i++){const source=SOURCES[i],wear=instance(garmentAssets[i],source.kind);wear.root.visible=false;actor.add(wear.root);worn.set(source.id,wear);const sample=instance(garmentAssets[i],source.kind);sample.root.position.fromArray(source.position);sample.root.visible=source.kind===galleryKind;world.add(sample.root);pose(sample,'neutral');color(sample,source.color);gallery.set(source.id,sample);const ghost=instance(garmentAssets[i],source.kind);world.add(ghost.root);pose(ghost,'neutral');color(ghost,source.color);ghost.root.traverse(node=>{if(!node.isMesh)return;node.castShadow=false;for(const material of Array.isArray(node.material)?node.material:[node.material]){material.transparent=true;material.opacity=.38;material.depthWrite=false;}});ghost.root.visible=false;ghosts.set(source.id,ghost);}
  const targetGeometry=new THREE.EdgesGeometry(new THREE.BoxGeometry(.75,DROP_Y.max-DROP_Y.min,.45));const target=new THREE.LineSegments(targetGeometry,new THREE.LineBasicMaterial({color:'#91a774',transparent:true,opacity:.7}));target.position.set(0,(DROP_Y.min+DROP_Y.max)/2,0);target.visible=false;world.add(target);
  let state=null;
  function updateGallery(){const close=state&&(state.view==='shoe-detail'||(state.camera.target[1]<=.45&&Math.hypot(...state.camera.position.map((p,i)=>p-state.camera.target[i]))<=3));racks.visible=galleryKind==='garment'&&!close;plinths.visible=galleryKind==='shoes'&&!close;for(const source of SOURCES)gallery.get(source.id).root.visible=source.kind===galleryKind&&!close;}
  function setGallery(kind){if(drag||!['garment','shoes'].includes(kind))return false;galleryKind=kind;updateGallery();return true;}
  function apply(next,{camera:changeCamera=true,preview=false}={}){state=next;updateGallery();pose(avatar,next.pose);for(const [id,item]of worn){const slot=item.kind==='shoes'?next.shoes:next.garment;item.root.visible=slot?.id===id;if(item.root.visible){pose(item,next.pose);color(item,slot.color);}}actor.updateMatrixWorld(true);if(changeCamera)setCamera(next.camera);target.material.color.set(preview?'#789853':'#b8a77c');}
  const raycaster=new THREE.Raycaster(),cursor=new THREE.Vector2();
  function ray(event){const rect=canvas.getBoundingClientRect();cursor.set((event.clientX-rect.left)/rect.width*2-1,-(event.clientY-rect.top)/rect.height*2+1);raycaster.setFromCamera(cursor,camera);}
  const visible=node=>{for(let p=node;p;p=p.parent)if(!p.visible)return false;return true;};
  function meshes(root){const result=[];root.traverse(n=>{if(n.isMesh&&visible(n))result.push(n);});return result;}
  function pick(event){ray(event);const choices=[];for(const source of SOURCES){const result=raycaster.intersectObjects(meshes(gallery.get(source.id).root),false)[0];if(result)choices.push({id:source.id,point:result.point,distance:result.distance,color:source.color});}return choices.sort((a,b)=>a.distance-b.distance)[0]||null;}
  function drop(event){const shoe=drag?.kind==='shoes';ray(event);const rect=canvas.getBoundingClientRect();if(event.clientX<rect.left||event.clientX>rect.right||event.clientY<rect.top||event.clientY>rect.bottom)return{valid:false,reason:'目标在试衣画面之外'};actor.updateMatrixWorld(true);const hit=raycaster.intersectObjects(meshes(actor),false)[0];if(!hit)return{valid:false,reason:shoe?'把整双鞋移到人体脚部':'把衣服移到人体胸腹区域'};const local=actor.worldToLocal(hit.point.clone());if(shoe){if(local.y<-.01||local.y>.30||Math.abs(local.x)>.36||local.z<-.18||local.z>.34)return{valid:false,reason:'请放到脚掌或脚踝，上身与更高的小腿不接受鞋履'};return{valid:true,reason:'鞋脚对齐 · 松手穿上整双'};}if(local.y<DROP_Y.min||local.y>DROP_Y.max||Math.abs(local.x)>.375||Math.abs(local.z)>.225)return{valid:false,reason:'请放到胸腹区域，头部、手臂和脚部不接受上装'};return{valid:true,reason:'位置合适 · 松手穿上'};}
  function begin(event,id,point){if(drag||locked)return false;const source=SOURCES.find(s=>s.id===id);if(!source||callbacks.dragStart?.({id,kind:source.kind,color:source.color})===false)return false;const anchorY=source.kind==='shoes'?.14:1.2;if(source.kind==='shoes'){target.scale.set(.72/.75,.31/(DROP_Y.max-DROP_Y.min),.52/.45);target.position.set(0,.145,.08);}else{target.scale.set(1,1,1);target.position.set(0,(DROP_Y.min+DROP_Y.max)/2,0);}
    const normal=camera.getWorldDirection(new THREE.Vector3());const plane=new THREE.Plane().setFromNormalAndCoplanarPoint(normal,point||new THREE.Vector3(0,anchorY,0));ray(event);const start=raycaster.ray.intersectPlane(plane,new THREE.Vector3());const origin=new THREE.Vector3(...source.position);drag={id,kind:source.kind,color:source.color,pointerId:event.pointerId,plane,offset:point&&start?origin.sub(start):new THREE.Vector3(0,-anchorY,0),start:[event.clientX,event.clientY],moved:false};controls.enabled=false;target.visible=true;canvas.style.cursor='grabbing';return true;}
  function update(event){if(!drag||event.pointerId!==drag.pointerId)return;ray(event);const point=raycaster.ray.intersectPlane(drag.plane,new THREE.Vector3());const ghost=ghosts.get(drag.id);if(point)ghost.root.position.copy(point).add(drag.offset);drag.moved||=Math.hypot(event.clientX-drag.start[0],event.clientY-drag.start[1])>=6;const result=drop(event);ghost.root.visible=drag.moved&&!result.valid;target.material.color.set(result.valid?'#729750':'#b8a77c');callbacks.dragChange?.({...result,moved:drag.moved});}
  function finish(event,cancelled=false){if(!drag||event.pointerId!==drag.pointerId)return;update(event);const current=drag,result=drop(event);drag=null;for(const ghost of ghosts.values())ghost.root.visible=false;target.visible=false;canvas.style.cursor='default';controls.enabled=cameraInteraction&&!locked;if(canvas.hasPointerCapture(current.pointerId))canvas.releasePointerCapture(current.pointerId);if(cancelled)callbacks.dragCancel?.();else callbacks.dragEnd?.({...result,moved:current.moved});}
  canvas.addEventListener('pointerdown',event=>{if(locked||drag){event.preventDefault();event.stopImmediatePropagation();return;}const selection=event.button===0?pick(event):null;if(selection){event.preventDefault();event.stopImmediatePropagation();if(begin(event,selection.id,selection.point))canvas.setPointerCapture(event.pointerId);}else if(cameraInteraction){held=true;cameraPointer=event.pointerId;}else{event.preventDefault();event.stopImmediatePropagation();}},true);
  canvas.addEventListener('pointermove',event=>{if(drag&&event.pointerId===drag.pointerId){update(event);event.stopImmediatePropagation();}else if(!locked)canvas.style.cursor=pick(event)?'grab':'default';},true);
  canvas.addEventListener('pointerup',event=>{if(drag){event.stopImmediatePropagation();finish(event);}else if(event.pointerId===cameraPointer){held=false;cameraPointer=null;}},true);canvas.addEventListener('pointercancel',event=>{if(drag){event.stopImmediatePropagation();finish(event,true);}else cancelCameraGesture();},true);canvas.addEventListener('lostpointercapture',()=>{if(drag){abortPointer();callbacks.dragCancel?.();}else if(held)forceReleaseCamera();});
  function release(){held=false;cameraPointer=null;if(locked){setCamera(lockedCamera);locked=false;lockedCamera=null;controls.enabled=cameraInteraction&&!drag;}callbacks.cameraEnd?.();}
  function cancelCameraGesture(){held=false;cameraPointer=null;if(locked){setCamera(lockedCamera);locked=false;lockedCamera=null;}callbacks.cameraCancel?.();controls.enabled=cameraInteraction&&!drag;}
  function forceReleaseCamera(){const id=cameraPointer;cancelCameraGesture();if(id!==null)canvas.dispatchEvent(new PointerEvent('pointercancel',{pointerId:id,bubbles:true}));}
  window.addEventListener('pointerup',release);window.addEventListener('pointercancel',cancelCameraGesture);
  controls.addEventListener('start',()=>{if(!applying&&!drag&&cameraInteraction&&!locked)callbacks.cameraStart?.();});controls.addEventListener('change',()=>{if(!applying&&!drag&&cameraInteraction&&!locked)callbacks.cameraChange?.(getCamera());});controls.addEventListener('end',()=>{if(!applying&&!drag&&cameraInteraction&&!locked&&!held)callbacks.cameraEnd?.();});
  function abortPointer(){const current=drag;drag=null;target.visible=false;for(const ghost of ghosts.values())ghost.root.visible=false;canvas.style.cursor='default';controls.enabled=cameraInteraction&&!locked;if(current&&canvas.hasPointerCapture(current.pointerId))canvas.releasePointerCapture(current.pointerId);}
  const resize=new ResizeObserver(()=>{const rect=host.getBoundingClientRect();if(!rect.width||!rect.height)return;camera.aspect=rect.width/rect.height;camera.updateProjectionMatrix();renderer.setSize(rect.width,rect.height,false);composer.setSize(rect.width,rect.height);});resize.observe(host);
  const projection=new THREE.Vector3();function frame(){if(disposed)return;controls.update();clampCamera();composer.render();for(const source of SOURCES){projection.set(source.position[0],source.kind==='shoes'?.41:1.1,source.position[2]).project(camera);callbacks.project?.(source.id,(projection.x+1)*host.clientWidth/2,(1-projection.y)*host.clientHeight/2,gallery.get(source.id).root.visible&&projection.z>=-1&&projection.z<=1);}frameId=requestAnimationFrame(frame);}frameId=requestAnimationFrame(frame);
  return{apply,setGallery,getCamera,setCamera,get cameraHeld(){return held;},releaseCamera:forceReleaseCamera,setCameraInteraction(value){cameraInteraction=!!value;controls.enabled=cameraInteraction&&!locked&&!drag;},cancelCamera(value){if(held){locked=true;lockedCamera=structuredClone(value);controls.enabled=false;}setCamera(value);},abortPointer,beginExternal(event,id){if(begin(event,id,null)){update(event);return true;}return false;},updateExternal:update,endExternal:finish,screenshot(){const visibility=target.visible;target.visible=false;for(const ghost of ghosts.values())ghost.root.visible=false;composer.render();const data=canvas.toDataURL('image/png');target.visible=visibility;return data;},dispose(){disposed=true;cancelAnimationFrame(frameId);resize.disconnect();window.removeEventListener('pointerup',release);window.removeEventListener('pointercancel',cancelCameraGesture);controls.dispose();composer.dispose();environment.dispose();renderer.dispose();}};
}
