import { createRequire } from 'node:module';
import { writeFile, mkdir, readdir, readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { spawn } from 'node:child_process';
import path from 'node:path';
const require=createRequire(import.meta.url);
let puppeteer;
try{puppeteer=require('puppeteer-core');}catch{puppeteer=require('../../../projects/008-pdoom-video/tools/node_modules/puppeteer-core');}
const project=fileURLToPath(new URL('../',import.meta.url));
const server=spawn(process.execPath,[project+'tools/serve.mjs'],{windowsHide:true,stdio:['ignore','pipe','pipe']});
await new Promise((resolve,reject)=>{server.stdout.once('data',resolve);server.once('error',reject);server.stderr.once('data',data=>{if(!String(data).includes('EADDRINUSE'))reject(new Error(String(data)));else resolve();});});
const backend=process.env.TIDEWATER_GPU_BACKEND||'default';
const args=['--no-sandbox','--no-first-run','--no-default-browser-check','--enable-unsafe-webgpu'];
if(backend!=='default')args.push(`--use-webgpu-adapter=${backend}`);
const browser=await puppeteer.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args,protocolTimeout:240000});
process.on('SIGINT',async()=>{await browser.close().catch(()=>{});server.kill();process.exit(130);});
const page=await browser.newPage();await page.setViewport({width:1440,height:1000,deviceScaleFactor:1});
const errors=[],requests=[];
page.on('pageerror',e=>{errors.push(e.message);console.log('PAGEERROR',e.message);});
page.on('console',m=>{if(m.type()==='error'){errors.push(m.text());console.log('CONSOLE',m.text().slice(0,800));}});
page.on('response',r=>{if(r.status()>=400){requests.push(`${r.status()} ${r.url()}`);console.log('HTTP',r.status(),r.url());}});
try{
  await page.goto('http://127.0.0.1:4196/',{waitUntil:'networkidle0',timeout:120000});
  console.log('OPEN',await page.title());
  console.log('GPU',backend,await page.evaluate(async()=>{const a=await navigator.gpu?.requestAdapter();return {available:!!navigator.gpu,adapter:!!a,info:a?{vendor:a.info?.vendor,architecture:a.info?.architecture,description:a.info?.description}:null};}));
  const progress=setInterval(async()=>console.log('PROGRESS',await page.$eval('#runtime-status',n=>n.textContent).catch(()=>'')),20000);
  try{await page.waitForFunction(()=>window.studio?.ready||document.getElementById('runtime-status').textContent==='3D 预览启动失败',{timeout:240000,polling:1000});}finally{clearInterval(progress);}
  if(!await page.evaluate(()=>studio.ready))throw new Error(await page.$eval('#toast',n=>n.textContent));
  console.log('READY');
  const settled=async()=>{const start=await page.evaluate(()=>document.getElementById('world-frame').contentWindow.tidewaterEditor.app.engine.frame);await page.waitForFunction(n=>document.getElementById('world-frame').contentWindow.tidewaterEditor.app.engine.frame>=n+24,{timeout:60000},start);};
  await settled();
  await page.screenshot({path:project+'assets/workbench-desktop.png'});
  const checks=[];
  const check=(name,value)=>{checks.push({name,pass:!!value});console.log(value?'PASS':'FAIL',name);if(!value)throw new Error(name);};
  check('六个对象与原渲染器就绪',await page.evaluate(()=>studio.scene.objects.length===6&&document.getElementById('world-frame').contentWindow.tidewaterEditor.app.fft!=null));
  await page.click('[data-prompt="改成日落，海浪平静一点"]');await page.click('#apply-prompt');
  check('文字修改真实环境',await page.evaluate(()=>{const r=document.getElementById('world-frame').contentWindow.tidewaterEditor;return studio.scene.environment.timeOfDay===18.3&&r.app.settings.timeOfDay===18.3&&r.app.fft.swell.scale===studio.scene.environment.swell;}));
  await page.click('[data-id="cabin-a"]');
  const before=await page.evaluate(()=>studio.scene.objects.find(o=>o.id==='cabin-a').x);
  await page.click('[data-prompt="把选中的物体向右移动10米"]');await page.click('#apply-prompt');
  check('对象指令改变真实几何',await page.evaluate(x=>{const r=document.getElementById('world-frame').contentWindow.tidewaterEditor,b=r.getEntityBounds('cabin-a');return studio.scene.objects.find(o=>o.id==='cabin-a').x===x+10&&Math.abs((b.min[0]+b.max[0])/2-(x+10))<.01&&b.max[1]-b.min[1]>5;},before));
  await page.click('#undo');check('撤销恢复对象',await page.evaluate(x=>studio.scene.objects.find(o=>o.id==='cabin-a').x===x,before));
  await page.click('#redo');check('重做恢复修改',await page.evaluate(x=>studio.scene.objects.find(o=>o.id==='cabin-a').x===x+10,before));
  await page.click('[data-prompt="锁定选中的物体"]');await page.click('#apply-prompt');
  check('锁定禁用表单并拒绝修改',await page.evaluate(()=>{let denied=false;try{studio.submitInstruction('向右移动10米');}catch{denied=true;}return denied&&document.getElementById('obj-x').disabled;}));
  check('未知复合指令原子拒绝',await page.evaluate(()=>{const before=JSON.stringify(studio.scene);try{studio.submitInstruction('改成日落，下雨');}catch{}return before===JSON.stringify(studio.scene);}));
  await page.click('[data-camera="pier"]');
  check('镜头控制生效',await page.evaluate(()=>studio.scene.camera.preset==='pier'&&document.getElementById('world-frame').contentWindow.tidewaterEditor.app.camera.position.x===30));
  await page.click('#save-scene');
  check('浏览器保存与JSON往返',await page.evaluate(()=>JSON.stringify(studio.scene)===JSON.stringify(JSON.parse(localStorage.getItem('tidewater-studio.v1')))));
  const saved=await page.evaluate(()=>studio.scene),downloadDir=path.join(project,'.runtime','browser-downloads',String(Date.now()));
  await mkdir(downloadDir,{recursive:true});
  const cdp=await browser.target().createCDPSession();await cdp.send('Browser.setDownloadBehavior',{behavior:'allow',downloadPath:downloadDir,eventsEnabled:true});
  cdp.on('Browser.downloadProgress',e=>console.log('DOWNLOAD',e.state));
  await page.click('#export-scene');
  let exported;
  for(let i=0;i<100&&!exported;i++){const names=await readdir(downloadDir);exported=names.find(n=>n.endsWith('.json'));if(!exported)await new Promise(r=>setTimeout(r,100));}
  check('导出实际JSON文件',exported&&JSON.stringify(JSON.parse(await readFile(downloadDir+'/'+exported,'utf8')))===JSON.stringify(saved));
  const imported={...saved,name:'导入验证场景'};await writeFile(downloadDir+'/import.json',JSON.stringify(imported));
  await (await page.$('#import-file')).uploadFile(downloadDir+'/import.json');await page.waitForFunction(()=>studio.scene.name==='导入验证场景');
  check('导入场景并可撤销',await page.evaluate(()=>{studio.undo();return studio.scene.name==='港湾海岛';}));
  await writeFile(downloadDir+'/invalid.json',JSON.stringify({...saved,version:999}));
  const previous=await page.evaluate(()=>JSON.stringify(studio.scene));
  await (await page.$('#import-file')).uploadFile(downloadDir+'/invalid.json');await page.waitForFunction(()=>document.getElementById('toast').textContent.startsWith('导入失败'));
  check('无效导入不破坏场景',await page.evaluate(before=>JSON.stringify(studio.scene)===before,previous));
  await page.click('#new-scene');await page.click('#undo');
  check('新建场景可恢复旧布局',await page.evaluate(before=>JSON.stringify(studio.scene)===before,previous));
  check('真实GPU截图读回',await page.evaluate(async()=>{const b=await document.getElementById('world-frame').contentWindow.tidewaterEditor.capture();return b.type==='image/png'&&b.size>20000;}));
  await page.click('[data-camera="overview"]');await page.click('[data-id="lighthouse"]');
  const position=await page.evaluate(()=>studio.scene.objects.find(o=>o.id==='lighthouse').x);
  await page.$eval('#obj-x',input=>{input.value='-90';input.dispatchEvent(new Event('change',{bubbles:true}));});
  check('属性面板连接真实对象',await page.evaluate(()=>{const b=document.getElementById('world-frame').contentWindow.tidewaterEditor.getEntityBounds('lighthouse');return studio.scene.objects.find(o=>o.id==='lighthouse').x===-90&&Math.abs((b.min[0]+b.max[0])/2+90)<.01;}));
  await page.click('#undo');
  check('属性撤销恢复位置',await page.evaluate(x=>studio.scene.objects.find(o=>o.id==='lighthouse').x===x,position));
  await settled();
  const hit=await page.evaluate(async()=>{
    const {Vector3}=await import('./runtime/src/engine/index.js');
    const iframe=document.getElementById('world-frame'),r=iframe.contentWindow.tidewaterEditor,b=r.getEntityBounds('lighthouse');
    const point=new Vector3(...b.min).add(new Vector3(...b.max)).multiplyScalar(.5).project(r.app.camera),rect=iframe.getBoundingClientRect();
    studio.select('boat');return {x:rect.x+(point.x+1)*rect.width/2,y:rect.y+(1-point.y)*rect.height/2};
  });
  await page.mouse.click(hit.x,hit.y);await page.waitForFunction(()=>studio.selectedId==='lighthouse',{timeout:10000});
  check('画面拾取选择真实对象',await page.evaluate(()=>studio.selectedId==='lighthouse'&&!document.getElementById('world-frame').contentDocument.pointerLockElement));
  await settled();await page.screenshot({path:project+'assets/workbench-sunset.png'});
  await page.evaluate(()=>studio.execute([{type:'preset',preset:'harbor'}],'恢复港湾环境'));
  await settled();await page.screenshot({path:project+'assets/workbench-desktop.png'});
  await page.setViewport({width:390,height:844,deviceScaleFactor:1});
  check('移动页面无横向溢出',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.screenshot({path:project+'assets/workbench-mobile.png',fullPage:true});
  check('无网页异常或缺失资源',!errors.length&&!requests.length);
  await writeFile(project+'checks/browser-results.json',JSON.stringify({date:new Date().toISOString(),viewport:[1440,1000],renderer:'Chrome WebGPU',backend,checks,errors,requests},null,2));
}catch(e){await mkdir(project+'assets',{recursive:true});await page.screenshot({path:project+'assets/browser-failure.png',fullPage:true}).catch(()=>{});console.error(e);process.exitCode=1;}
finally{await browser.close();server.kill();}
