import { History,initialState,validateState,cameraForView,VIEWS } from './core.js';
import { createLandmark } from './scene.js';
const $=id=>document.getElementById(id),KEY='atelier-landmark-workspace-v1';
let history=new History(),scene,cards=[],cameraEnding=false,gestureTimer,toastTimer,timePointerHeld=false,timeCancelled=false;
try{const saved=localStorage.getItem(KEY);if(saved)history=new History(validateState(JSON.parse(saved)));}catch{$('save-status').textContent='旧配置无法读取，已打开新工作区';}
const timeText=value=>{const minutes=Math.round(value*60);return `${String(Math.floor(minutes/60)).padStart(2,'0')}:${String(minutes%60).padStart(2,'0')}`;};
function toast(message){clearTimeout(toastTimer);$('toast').textContent=message;$('toast').hidden=false;toastTimer=setTimeout(()=>$('toast').hidden=true,2300);}
function persist(){try{localStorage.setItem(KEY,JSON.stringify(history.pending?.state??history.current));$('save-status').textContent='已保存在本机';}catch{$('save-status').textContent='本地空间不足，请备份 JSON';}}
function refresh({camera=false}={}){const s=history.current;scene?.apply(s,{camera});$('time').value=s.time;$('time-output').value=timeText(s.time);$('lights').setAttribute('aria-pressed',s.lights);$('undo').disabled=!history.past.length;$('redo').disabled=!history.future.length;$('view-name').textContent=VIEWS[s.view]?.name??'自由视角';document.querySelector('.stage').classList.toggle('night',s.time>=20);document.querySelector('.stage').classList.toggle('focus-view',s.view!=='overview');document.querySelectorAll('[data-time]').forEach(b=>b.classList.toggle('active',Number(b.dataset.time)===s.time));document.querySelectorAll('[data-view]').forEach(b=>{b.classList.toggle('active',b.dataset.view===s.view);b.setAttribute('aria-pressed',b.dataset.view===s.view);});document.querySelectorAll('[data-hotspot]').forEach(b=>{b.classList.toggle('active',b.dataset.hotspot===s.hotspot);b.setAttribute('aria-pressed',b.dataset.hotspot===s.hotspot);});const card=cards.find(c=>c.id===s.hotspot);if(card){$('knowledge-kicker').textContent=card.kicker;$('knowledge-title').textContent=card.title;$('knowledge-body').textContent=card.body;$('knowledge-observation').textContent=card.observation;$('knowledge-boundary').textContent=card.knowledgeBoundary;$('knowledge-sources').replaceChildren(...card.sources.map(source=>{const a=document.createElement('a');a.href=source.url;a.textContent=source.title+' ↗';a.target='_blank';a.rel='noopener';return a;}));}else{$('knowledge-kicker').textContent='DOCUMENTED / NOT INFERRED';$('knowledge-title').textContent='从观察走向理解';$('knowledge-body').textContent='点击画面中的编号或资料卡，阅读博物馆官方记载。资料入口关联学习主题，不代表历史事件的精确位置。';$('knowledge-observation').textContent='';$('knowledge-boundary').textContent='简化中空外部打印模型，没有原色纹理或完整室内；尺度只用于展示。';$('knowledge-sources').replaceChildren();}}
function finish(){clearTimeout(gestureTimer);cameraEnding=false;try{if(history.pending?.label==='自由观察'&&scene){history.current.camera=scene.getCamera();scene.cancelCamera(history.current.camera);}if(history.commit()){persist();refresh();}}catch(error){refresh({camera:true});toast(error.message);}}
function cancel(){clearTimeout(gestureTimer);cameraEnding=false;if(timePointerHeld)timeCancelled=true;const cameraPending=history.pending?.label==='自由观察';if(history.cancel()){if(cameraPending)scene?.cancelCamera(history.current.camera);refresh({camera:true});}}
function edit(label,fn,{camera=false}={}){finish();try{history.edit(label,fn);refresh({camera});persist();}catch(error){refresh({camera:true});toast(error.message);}}
function selectHotspot(id){edit('阅读知识卡',s=>{s.hotspot=id;});}
for(const [id,view] of Object.entries(VIEWS)){const b=document.createElement('button');b.textContent=view.name;b.dataset.view=id;b.addEventListener('click',()=>edit('切换观察视角',s=>{s.view=id;s.camera=cameraForView(id);},{camera:true}));$('view-options').append(b);}
document.querySelectorAll('[data-time]').forEach(b=>b.addEventListener('click',()=>edit('切换展览时段',s=>{s.time=Number(b.dataset.time);})));$('lights').addEventListener('click',()=>edit('切换展览补光',s=>{s.lights=!s.lights;}));
$('time').addEventListener('pointerdown',()=>{timePointerHeld=true;timeCancelled=false;});window.addEventListener('pointerup',()=>{timePointerHeld=false;timeCancelled=false;});window.addEventListener('pointercancel',()=>{timePointerHeld=false;timeCancelled=false;});
$('time').addEventListener('input',()=>{if(timeCancelled){$('time').value=history.current.time;return;}const value=Number($('time').value);if(history.pending&&history.pending.label!=='调整展览时段')finish();if(!history.pending)history.begin('调整展览时段');history.current.time=value;refresh();});$('time').addEventListener('change',finish);
$('undo').addEventListener('click',()=>{finish();if(history.undo()){refresh({camera:true});persist();toast('已撤销');}});$('redo').addEventListener('click',()=>{finish();if(history.redo()){refresh({camera:true});persist();toast('已重做');}});$('save').addEventListener('click',()=>{finish();persist();toast('观察配置已保存在本机');});$('reset-view').addEventListener('click',()=>edit('恢复总览',s=>{s.view='overview';s.camera=cameraForView('overview');},{camera:true}));
document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));$('about').addEventListener('click',()=>{finish();$('about-dialog').showModal();});$('retry').addEventListener('click',()=>location.reload());
$('backup').addEventListener('click',()=>{finish();$('configuration').value=JSON.stringify(history.current,null,2);$('config-error').textContent='';$('backup-dialog').showModal();});$('restore-config').addEventListener('click',()=>{try{const raw=$('configuration').value;if(raw.length>32768)throw new Error('配置最多 32 KiB');const next=validateState(JSON.parse(raw));finish();history.edit('打开地标配置',()=>next);refresh({camera:true});persist();$('backup-dialog').close();toast('已恢复地标配置');}catch(error){$('config-error').textContent='无法应用：'+error.message;}});
$('download-config').addEventListener('click',()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(history.current,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='atelier-landmark.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
for(const mode of ['orbit','pan'])$(mode+'-mode').addEventListener('click',()=>{finish();scene?.setNavigation(mode);$('orbit-mode').setAttribute('aria-pressed',mode==='orbit');$('pan-mode').setAttribute('aria-pressed',mode==='pan');$('navigation-hint').textContent=mode==='pan'?'拖动平移 · 滚轮缩放 · 切换可环绕':'拖动环绕 · 滚轮缩放 · 右键平移';$('canvas-host').setAttribute('aria-label',mode==='pan'?'拖动平移建筑视角，滚轮缩放':'拖动环绕建筑，滚轮缩放，右键平移');});
$('snapshot').addEventListener('click',()=>{finish();if(!scene)return;$('snapshot-image').src=scene.screenshot();$('snapshot-dialog').showModal();});
window.addEventListener('keydown',event=>{if(event.key==='Escape'){cancel();return;}if(document.querySelector('dialog[open]')||['INPUT','TEXTAREA'].includes(event.target.tagName))return;if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='z'){event.preventDefault();$(event.shiftKey?'redo':'undo').click();}});window.addEventListener('blur',()=>{cancel();scene?.releaseCamera();});window.addEventListener('pointercancel',cancel);window.addEventListener('beforeunload',persist);
refresh();
try{const response=await fetch('./assets/landmark/hotspots.json');if(!response.ok)throw new Error('知识卡无法读取');cards=(await response.json()).hotspots;cards.forEach((card,index)=>{const b=document.createElement('button');b.dataset.hotspot=card.id;const n=document.createElement('span');n.textContent=String(index+1).padStart(2,'0');b.append(n,document.createTextNode(card.title));b.addEventListener('click',()=>selectHotspot(card.id));$('knowledge-options').append(b);const marker=document.createElement('button');marker.className='hotspot';marker.id='marker-'+card.id;marker.dataset.hotspot=card.id;marker.textContent=index+1;marker.setAttribute('aria-label','资料入口 '+(index+1)+'：'+card.title);marker.addEventListener('click',()=>selectHotspot(card.id));$('markers').append(marker);});scene=await createLandmark($('canvas-host'),{project(id,x,y,visible){const marker=$('marker-'+id);marker.style.left=x+'px';marker.style.top=y+'px';marker.hidden=!visible;},cameraStart(){finish();history.begin('自由观察');},cameraChange(camera){if(history.pending?.label!=='自由观察')return;history.current.camera=camera;history.current.view='custom';$('view-name').textContent='自由视角';if(cameraEnding){clearTimeout(gestureTimer);gestureTimer=setTimeout(finish,180);}},cameraEnd(){if(history.pending?.label!=='自由观察')return;cameraEnding=true;clearTimeout(gestureTimer);gestureTimer=setTimeout(finish,180);}});refresh({camera:true});$('loading').hidden=true;}catch(error){$('loading').hidden=true;$('load-error').hidden=false;$('error-detail').textContent=error.message;console.error(error);}
