import {History,initialState,validateState,gesture,appendTrial,sampleJump,jumpDuration,setView,setHeight,findTrial,selectTrial} from './core.js';
import {createSkate} from './scene.js';
const $=id=>document.getElementById(id), KEY='atelier-skate-workspace-v1';
const labels={preparation:'准备起跳',air:'腾空',landing:'落地缓冲',done:'站稳',idle:'站姿 · 等待手势'};
let history=new History(),scene,motion=null,dragging=false,frame,cameraTimer,toastTimer,storeUnreadable=false,heightCancelled=false,heightHeld=false;
try{const raw=localStorage.getItem(KEY);if(raw)history=new History(validateState(JSON.parse(raw)));}catch{storeUnreadable=true;$('save-status').textContent='旧练习无法读取，请备份或明确保存';}
function toast(text){clearTimeout(toastTimer);$('toast').textContent=text;$('toast').hidden=false;toastTimer=setTimeout(()=>$('toast').hidden=true,2200);}
function persist({explicit=false}={}){if(storeUnreadable&&!explicit)return;try{localStorage.setItem(KEY,JSON.stringify(history.pending?.state??history.current));storeUnreadable=false;$('save-status').textContent='已保存在本机';}catch{$('save-status').textContent='保存未完成，请备份 JSON';}}
function updateMotion(pose={phase:'idle',progress:0,boardY:0}){$('phase').textContent=labels[pose.phase];$('motion-label').textContent=motion?.kind==='gesture'?labels[pose.phase]:motion?`观察 · ${labels[pose.phase]}`:'准备好了';$('motion-progress').value=pose.progress;$('live-height').textContent=pose.boardY.toFixed(2);$('scrub').value=pose.progress;document.querySelectorAll('[data-phase]').forEach(el=>el.classList.toggle('active',el.dataset.phase===pose.phase));$('contact-status').textContent=pose.boardY>0?'支撑点对齐':'站稳';}
function refresh(){const s=history.current,busy=!!motion||dragging;$('undo').disabled=!history.canUndo;$('redo').disabled=!history.canRedo;$('height').value=s.height;$('height').disabled=busy||!scene;$('height-output').value=s.height.toFixed(2);$('preview').disabled=busy||!scene;$('cancel-motion').disabled=!busy;$('scrub').disabled=!motion||motion.kind==='gesture';$('resume-motion').disabled=!motion||motion.kind==='gesture'||!motion.paused;$('replay').disabled=busy||!s.selectedTrial||!findTrial(s,s.selectedTrial)||!scene;$('clear').disabled=busy||!s.trials.length;$('trial-count').value=`${s.trials.length} / 40`;$('drag-feedback').hidden=!dragging;
  document.querySelectorAll('[data-view]').forEach(b=>{b.setAttribute('aria-pressed',b.dataset.view===s.view);b.disabled=busy;});
  const buttons=[...s.trials].reverse().map(trial=>{const b=document.createElement('button');b.setAttribute('aria-pressed',trial.id===s.selectedTrial);b.setAttribute('aria-label',`选择练习 ${trial.id}，高度 ${trial.height.toFixed(2)}`);const label=document.createElement('span');label.textContent=`第 ${trial.id} 次 · ${trial.height.toFixed(2)}`;const sub=document.createElement('small');sub.textContent=`上拖 ${Math.round(trial.rise)} px`;b.append(label,sub);b.disabled=busy;b.addEventListener('click',()=>edit('选择练习',state=>selectTrial(state,trial.id)));return b;});if(!buttons.length){const p=document.createElement('p');p.className='empty-record';p.textContent='还没有完成的跳跃。先抓住画面中的滑板，向上拖一次。';buttons.push(p);}$('trial-list').replaceChildren(...buttons);
}
function finishCamera(){clearTimeout(cameraTimer);if(scene?.cameraHeld())return;if(history.pending?.label==='观察视角'){try{history.current.camera=scene.getCamera();if(history.commit())persist();}catch(error){scene.setCamera(history.current.camera);toast(error.message);}refresh();}}
function idle(){scene?.applyPose({phase:'idle',time:0,crouch:0,boardY:0});scene?.lock(false);updateMotion();}
function cancel(){clearTimeout(cameraTimer);const wasMotion=!!motion;motion=null;dragging=false;cancelAnimationFrame(frame);scene?.cancelDrag();if(history.pending)history.cancel();if(heightHeld)heightCancelled=true;if(scene){scene.cancelCamera(history.current.camera);idle();}refresh();if(wasMotion)toast('动作已取消，原记录保持');}
function edit(label,fn,{camera=false,propagate=false}={}){if(motion||dragging)cancel();finishCamera();try{if(history.edit(label,fn))persist();if(camera)scene?.setCamera(history.current.camera);refresh();return true;}catch(error){refresh();if(propagate)throw error;toast(error.message);return false;}}
function tick(now){if(!motion)return;const active=motion;if(!active.paused)active.time=Math.min(jumpDuration(active.height),(now-active.start)/1000);const pose=sampleJump(active.time,active.height);scene.applyPose(pose);updateMotion(pose);if(pose.phase==='done'&&!active.paused){motion=null;scene.lock(false);if(active.kind==='gesture'){try{history.current=appendTrial(history.current,active.gesture);history.commit();persist();toast('已完成一次跳跃；可撤销或重播');}catch(error){history.cancel();toast(error.message);}}idle();refresh();return;}frame=requestAnimationFrame(tick);}
function startMotion(height,kind,record=null){finishCamera();if(motion||dragging)cancel();if(kind==='gesture')history.begin('完成滑板跳跃');motion={kind,height,gesture:record,time:0,start:performance.now(),paused:false};scene.lock(true);refresh();frame=requestAnimationFrame(tick);}
$('preview').addEventListener('click',()=>{if(scene&&!motion)startMotion(history.current.height,'preview');});
$('replay').addEventListener('click',()=>{const trial=history.current.selectedTrial&&findTrial(history.current,history.current.selectedTrial);if(trial&&scene&&!motion)startMotion(trial.height,'replay');});
$('scrub').addEventListener('input',()=>{if(!motion||motion.kind==='gesture')return;motion.paused=true;motion.time=Number($('scrub').value)*jumpDuration(motion.height);scene.applyPose(sampleJump(motion.time,motion.height));updateMotion(sampleJump(motion.time,motion.height));refresh();});
$('resume-motion').addEventListener('click',()=>{if(!motion||!motion.paused)return;motion.start=performance.now()-motion.time*1000;motion.paused=false;refresh();});
$('cancel-motion').addEventListener('click',cancel);
$('height').addEventListener('pointerdown',()=>{heightHeld=true;heightCancelled=false;});window.addEventListener('pointerup',()=>{heightHeld=false;heightCancelled=false;});
$('height').addEventListener('input',()=>{if(heightCancelled){$('height').value=history.current.height;return;}finishCamera();if(!history.pending)history.begin('调整辅助预览高度');try{history.current=setHeight(history.current,Number($('height').value));$('height-output').value=history.current.height.toFixed(2);}catch(error){history.cancel();toast(error.message);}refresh();});
$('height').addEventListener('change',()=>{if(heightCancelled)return;if(history.pending?.label==='调整辅助预览高度'){if(history.commit())persist();refresh();}});
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>edit('切换观察视角',s=>setView(s,b.dataset.view),{camera:true})));
$('clear').addEventListener('click',()=>edit('清空练习记录',s=>({...s,trials:[],selectedTrial:null})));
for(const id of ['undo','redo'])$(id).addEventListener('click',()=>{if(motion||dragging||history.pending){cancel();toast('未完成动作已取消');return;}if(history[id]()){scene?.setCamera(history.current.camera);idle();persist();refresh();toast(id==='undo'?'已撤销':'已重做');}});
$('save').addEventListener('click',()=>{if(motion||dragging)cancel();finishCamera();if(history.pending)history.commit();persist({explicit:true});refresh();});
$('backup').addEventListener('click',()=>{if(motion||dragging)cancel();finishCamera();if(history.pending)history.commit();$('json-text').value=JSON.stringify(history.current,null,2);$('json-message').textContent='';$('json-dialog').showModal();});
$('import-json').addEventListener('click',()=>{try{const raw=$('json-text').value;if(new TextEncoder().encode(raw).length>32768)throw new Error('练习配置最多32 KiB');const next=validateState(JSON.parse(raw));edit('打开练习配置',()=>next,{camera:true,propagate:true});$('json-dialog').close();toast('已恢复完整练习');}catch(error){$('json-message').textContent='没有应用：'+error.message;}});
function download(data,name,type){const url=URL.createObjectURL(new Blob([data],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1500);}
$('download-json').addEventListener('click',()=>download(JSON.stringify(history.current,null,2),'atelier-skate.json','application/json'));
$('snapshot').addEventListener('click',()=>{if(!scene)return;if(motion?.kind==='gesture'){toast('请先完成或取消动作，再保留图片');return;}if(motion)motion.paused=true;$('snapshot-image').src=scene.screenshot();$('snapshot-dialog').showModal();refresh();});
$('download-snapshot').addEventListener('click',()=>{const a=document.createElement('a');a.href=$('snapshot-image').src;a.download='atelier-skate.png';a.click();});
document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));$('retry').addEventListener('click',()=>location.reload());
window.addEventListener('keydown',event=>{if(event.key==='Escape'){cancel();return;}if(document.querySelector('dialog[open]')||['INPUT','TEXTAREA'].includes(event.target.tagName))return;if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='z'){event.preventDefault();$(event.shiftKey?'redo':'undo').click();}});
window.addEventListener('blur',cancel);window.addEventListener('pagehide',()=>persist());
refresh();
try{scene=await createSkate($('canvas-host'),{
  project(x,y,visible){$('board-marker').style.left=x+'px';$('board-marker').style.top=y+'px';$('board-marker').hidden=!visible||dragging||!!motion;},
  contact({gap}){$('contact-status').dataset.supportGap=gap.toFixed(8);},
  dragStart(){finishCamera();dragging=true;history.begin('滑板上拖手势');$('drag-distance').textContent='0 px';refresh();},
  dragChange(rise,dx){$('drag-distance').textContent=`${Math.round(Math.max(0,rise))} px`;const valid=rise>=24&&Math.abs(dx)<=100;$('drag-feedback').classList.toggle('ready',valid);$('phase').textContent=valid?'松手起跳':'继续向上拖 · 至少 24 px';},
  dragEnd(input){dragging=false;history.cancel();const result=gesture(input.rise,input.dx,input.durationMs);if(result)startMotion(result.height,'gesture',result);else{idle();refresh();toast('未触发：向上至少24 px，并保持在滑板上方');}},
  dragCancel(){dragging=false;history.cancel();idle();refresh();},
  cameraStart(){if(history.pending&&history.pending.label!=='观察视角')history.commit();if(!history.pending)history.begin('观察视角');},
  cameraChange(camera){if(history.pending?.label!=='观察视角')return;history.current.camera=camera;history.current.view='custom';clearTimeout(cameraTimer);cameraTimer=setTimeout(finishCamera,180);},
  cameraEnd(){clearTimeout(cameraTimer);cameraTimer=setTimeout(finishCamera,160);},
});scene.setCamera(history.current.camera);idle();$('loading').hidden=true;refresh();}catch(error){$('loading').hidden=true;$('load-error').hidden=false;$('error-detail').textContent=error.message;console.error(error);}
